Modifications to enable using FDDA nudging with input prep.
FDDA nudging allows you to push the model meteorology toward the reanalysis
meteorology that is already used to generate the initial and boundary
conditions. When FDDA nudging is active (grid_fdda=1 in the &fdda section of the
WRF namelist), real.exe will generate an additional file that contains the
necessary information for nudging. Since this increases the time real takes to
run, we don't want that to happen until the last execution of real.exe during
the input preparation.

MODIFIED FILES:
    CONFIG/autowrf_namelist_main.py - the check-wrf-opt and check-wps-opt
command line methods changed so that, if any checked option cannot be found, the
exit code 2 is given rather than a python error. get-{wrf,wps}-opt changed so
that in the same situation the exit code is 2 (rather than 1).

    PREPINPUT/prepmegan - turns off grid_fdda if necessary before running
real.exe.

    PREPINPUT/prepnei_convert - same idea as prepmegan.

    PREPINPUT/prepmozbc - the python program tempmod command before the last
real.exe should restore grid_fdda if it was on, but this now double-checks that
the expected behavior occurs.

    prepinpt - sets FDDA_ON to reflect whether FDDA nudging is requested in the
namelist.

diff --git a/PREPINPUT/prepmozbc b/PREPINPUT/prepmozbc
--- a/PREPINPUT/prepmozbc
+++ b/PREPINPUT/prepmozbc
@@ -91,6 +91,30 @@ if $missingfiles; then
     exit 1
 fi
 
+# Also double check the grid_fdda setting. if $FDDA_ON was set in the main prepinpt script,
+# then grid_fdda should be on here. If not, something weird is going on.
+if [[ $FDDA_ON == 1 ]]; then
+    python $pyprog check-wrf-opt --grid_fdda=1
+    fdda_check=$?
+    if [[ $fdda_check == 1 ]]; then
+        echo "Problem with prepmozbc: the main prepinpt script found that grid_fdda==1 in namelist.input"
+        echo "at the beginning of the input prep run and set the env. variable FDDA_ON to 1, but grid_fdda"
+        echo "did not get returned to 1 in the namelist before running the last instance of real.exe"
+        exit 1
+    elif [[ $fdda_check == 2 ]]; then
+        echo "Problem with prepmozbc: the main prepinpt script found that grid_fdda==1 in namelist.input"
+        echo "at the beginning of the input prep run and set the env. variable FDDA_ON to 1, but grid_fdda"
+        echo "does not exist in the namelist now." 
+        exit 1
+    elif [[ $fdda_check != 0 ]]; then
+        echo "Problem with prepmozbc: checking for the value of grid_fdda failed with an exit code of $fdda_check"
+        echo "Typically, the only exit codes should be 0 (option is correct), 1 (option is wrong), or 2"
+        echo "(option not found in namelist). Has $pyprog"
+        echo "been updated since the last time prepmozbc was edited?"
+        exit 1 
+    fi
+fi
+
 ./real.exe
 realexit=$?
 if [ $realexit -ne 0 ]; then
