Untested modifications to PREPINPT code to support lat-lon map projections.
Lat-lon projections are unique for WRF in that the WPS namelist expects dx and
dy to be given in degrees, but the WRF namelist wants them in meters. In order
to accomplish this, I decided to have autowrfchem wait until the met data has
been prepared, then read the DX and DY global attributes (which are given in
meters) and insert these into the WRF namelist.

This required some modification of the python program used to manage the namelists,
because it had been previously designed to ensure that changes to the common
options of WRF and WPS were guaranteed to match. This was handled by requiring
the --force-wrf-only flag given when issuing the "mod" or "modify" command
to this program.

PREPINPUT/prepwps then had to be modified to check if a lat-lon projection is in
use, and if so, use ncdump to get the dx and dy global attributes and set their
values in namelist.input.

Finally, PREPINPUT/precheck was modified to include a check that the map
projection is 'lambert' or 'polar' unless the 'met-only' flag is specified.
This ensures that an NEI-compatible projection is used if NEI emissions are used.

diff --git a/PREPINPUT/prepwps b/PREPINPUT/prepwps
--- a/PREPINPUT/prepwps
+++ b/PREPINPUT/prepwps
@@ -104,3 +104,53 @@ p="../../WPS/met_em*"
 for f in $p; do
     ln -s $f
 done
+
+# If using lat-lon map projection, then we need to modify the
+# WRF namelist permanently to account for the fact that the
+# dx dy in the WPS namelist is ONLY IN THAT CASE given in degrees
+# but the WRF namelist still expects meters
+mapproj=`$pyprog get-wps-opt --no-quotes --map_proj`
+if [ "$mapproj" == "lat-lon" ]; then
+    which ncdump > /dev/null
+    if [ $? -ne 0 ]; then
+        echo ""
+        echo "***********************************************************************************"
+        echo "WARNING: You are using a LAT-LON map projection and do not have NCDUMP on your path"
+        echo "  AUTOWRFCHEM uses NCDUMP to convert DX,DY in the WPS namelist into meters for WRF."
+        echo "  Without NCDUMP, you will need to manually edit namelist.input in"
+        echo "  $mydir/../CONFIG"
+        echo "  to get DX and DY right."
+        echo "***********************************************************************************"
+        echo ""
+    else
+        regex="[0-9]+"
+        metfile=`ls -1 met_em* | head -n 1`
+        dx=`ncdump -h $metfile | grep ":DX"`
+        if [[ $dx =~ $regex ]]; then
+            dxNum=${BASH_REMATCH[0]}
+        fi
+        dy=`ncdump -h | grep ":DY"`
+        if [[ $dy =~ $regex ]]; then
+            dyNum=${BASH_REMATCH[0]}
+        fi
+
+        if [ -z "$dxNum" ] || [ -z "$dyNum" ]; then
+            echo ""
+            echo "*****************************************************"
+            echo "Failed to obtain DX or DY from the meteorology files."
+            echo "You will need to manually edit namelist.input in"
+            echo "$mydir/../CONFIG"
+            echo "to get DX and DY right."
+            echo "*****************************************************"
+            echo ""
+        else
+            echo ""
+            echo "***************************************************************************"
+            echo "LAT-LON map proj: Setting DX and DY in namelist.input to match met_em files"
+            echo "***************************************************************************"
+            echo ""
+            $pyprog mod --force-wrf-only --dx=$dxNum
+            $pyprog mod --force-wrf-only --dy=$dyNum
+        fi
+    fi
+fi
