Number of user-friendliness improvements
    * namelist.input.template: added the scale_nei_emiss and scale_closest_year options
      to the chem namelist. These are implemented in commits a263d29 through 52cf5d6 of
      the WRF-Chem-R2SMH repo (https://github.com/CohenBerkeleyLab/WRF-Chem-R2SMH)
    * PREPINPUT/precheck now checks that mozbcFile has been set i.e. is not a zero-length
      string; if it is, then the error message for "Cannot find data/$mozbcFile" is very
      confusing as it looks like its saying that it cannot find the data link.
    * PREPINPUT/prepnei_convert: convert_emiss error messages now correctly give the
      convert_emiss exit code rather than the real.exe exit code.
    * Many files: modified or added messages before `exit 1` calls to explicitly indicate
      that the program is aborting.

diff --git a/PREPINPUT/splitwps b/PREPINPUT/splitwps
--- a/PREPINPUT/splitwps
+++ b/PREPINPUT/splitwps
@@ -38,7 +38,7 @@ if [[ ! -z $subfile ]]; then
     dosubmit=true
     grep '#AUTOWRFEXEC' "$subfile" >& /dev/null
     if [[ $? != 0 ]]; then
-        echo "File passed with --subfile= must have a line containing '#AUTOWRFEXEC' to be replaced with the necessary commands." >&2
+        echo "File passed with --subfile= must have a line containing '#AUTOWRFEXEC' to be replaced with the necessary commands. Aborting split WPS run." >&2
         exit 1
     fi
 fi
